---
- name: "Configure database server"
  hosts: db01

  user: vagrant
  become: yes
  vars_files:
    - vars/main.yaml
  vars:
    - dbname: "db01"
    - dbusername: "root"
    - dbpassword: "devopsmaonamassa"
  roles:
    - default-os-configuration
    - role: geerlingguy.mysql