Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = "docker"
    config.vm.network "private_network", ip: "10.10.1.2"
    config.vm.synced_folder "./share", "/vagrant", type: "nfs"
    config.vm.provision "shell", path: "provision.sh"
  end