---
- name: Configure ansible lab hosts
      lineinfile: 
        dest: /etc/hosts
        state: present
        line: "{{item}}"
      with_items:
        - 10.10.0.2 control-node
        - 10.10.0.3 app01
        - 10.10.0.4 db01

- name: Upgrade O.S. packets
  yum:
    name: '*'
    state: latest
    
- name: git client installation
    yum:
      name: git
      state: latest
      