pipeline {
    agent any
    stages{
        stage('Docker image build'){
            steps{
                sh 'docker build -t devops/app .'
            }
        }
        stage('Up test containers- redis and app'){
            steps{
                sh 'docker-compose up --build -d'
            }
        }
        stage('Wait for container go up'){
            steps{
                sh 'sleep 15'
            }
        }
        stage('SonarQube validation'){
            steps{
                script{
                    scannerHome = tool 'sonar-scanner';
                }
                withSonarQubeEnv('sonar-server'){
                    sh "${scannerHome}/bin/sonar-scanner / 
                    -Dsonar.ProjectKey=redis-app /
                    -Dsonar.sources=. /
                    -Dsonar.host.url=${env.SONAR_HOST_URL} /
                    -Dsonar.login=${env.SONAR_TOKEN_AUTH}"

                }
            }
        }
        stage('QualityGate'){
            steps{
                waitForQualityGate abortPipeline: true
            }
        }
        stage('application test'){
            steps{
                sh 'chmod +x test-app.sh'
                sh './test-app.sh'
            }            
        }
        stage('Shutdown test containers'){
            steps{
                sh 'docker-compose down'
            }            
        }
    }
}